version: '3.9'
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  server:
    build: ./server
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/sealens
      - PYTHON_BIN=python
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
volumes:
  mongo-data: